/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * mini-stim-server-soma
 * OpenAPI spec version: 0.1.0
 */
export type ActorType = (typeof ActorType)[keyof typeof ActorType];

export const ActorType = {
  account: "account",
  soul: "soul",
  system: "system",
} as const;

export type String = string;

export interface Compact {
  created_at: String;
  end_session_seq: number;
  id: string;
  start_session_seq: number;
  summary: string;
  turn_id: string;
}

export interface SessionProfile {
  created_at: String;
  /** @nullable */
  desc?: string | null;
  session_id: string;
  /** @nullable */
  title?: string | null;
  updated_at: String;
}

export interface Session {
  created_at: String;
  /** @nullable */
  fork_point?: number | null;
  id: string;
  /** @nullable */
  parent_session_id?: string | null;
  updated_at: String;
}

export interface SessionSummary {
  profile: SessionProfile;
  session: Session;
}

export interface CreateSessionResponse {
  session: SessionSummary;
}

export interface ErrorResponse {
  code: string;
  message: string;
}

export interface HealthResponse {
  ok: boolean;
  service: string;
}

export type MessagePart =
  | {
      text: string;
      type: "text";
    }
  | {
      data_base64: string;
      mime_type: string;
      type: "image";
    };

export interface MessageContent {
  parts: MessagePart[];
}

export type MessageState = (typeof MessageState)[keyof typeof MessageState];

export const MessageState = {
  pending: "pending",
  fixed: "fixed",
} as const;

export interface Message {
  actor_id: string;
  actor_type: ActorType;
  content: MessageContent;
  created_at: String;
  deleted_at?: null | String;
  id: string;
  state: MessageState;
  updated_at: String;
  version: number;
}

export interface SendSessionRequest {
  content: MessagePart[];
}

export interface SessionMessageRef {
  created_at: String;
  message_id: string;
  session_id: string;
  session_seq: number;
}

export interface SessionMessage {
  content_text: string;
  message: Message;
  relation: SessionMessageRef;
}

export interface SoulProfile {
  /** @nullable */
  avatar_ref?: string | null;
  avatar_seed: string;
  created_at: String;
  /** @nullable */
  desc?: string | null;
  nickname: string;
  soul_id: string;
  updated_at: String;
}

export interface SoulSession {
  created_at: String;
  /** @nullable */
  fork_point?: number | null;
  id: string;
  last_seen_session_seq: number;
  next_seq: number;
  /** @nullable */
  parent_soul_session_id?: string | null;
  provider_state?: unknown;
  session_id: string;
  session_memory: string;
  soul_id: string;
  updated_at: String;
}

export interface ToolCall {
  arguments: unknown;
  created_at: String;
  id: string;
  tool_name: string;
  turn_id: string;
}

export interface ToolResult {
  created_at: String;
  /** @nullable */
  error_text?: string | null;
  id: string;
  output?: unknown;
  tool_call_id: string;
}

export type TurnStatus = (typeof TurnStatus)[keyof typeof TurnStatus];

export const TurnStatus = {
  running: "running",
  completed: "completed",
  failed: "failed",
} as const;

export type TurnTriggerType =
  (typeof TurnTriggerType)[keyof typeof TurnTriggerType];

export const TurnTriggerType = {
  session_send: "session_send",
  system: "system",
} as const;

export interface Turn {
  base_soul_session_seq: number;
  created_at: String;
  /** @nullable */
  end_soul_session_seq?: number | null;
  /** @nullable */
  error_text?: string | null;
  finished_at?: null | String;
  id: string;
  input_through_session_seq: number;
  soul_session_id: string;
  status: TurnStatus;
  /** @nullable */
  trigger_ref?: string | null;
  trigger_type: TurnTriggerType;
  updated_at: String;
}

export interface SendSessionResponse {
  assistant_message: SessionMessage;
  session: SessionSummary;
  soul_profile: SoulProfile;
  soul_session: SoulSession;
  tool_calls: ToolCall[];
  tool_results: ToolResult[];
  turn: Turn;
  user_message: SessionMessage;
}

export interface SessionDetail {
  messages: SessionMessage[];
  profile: SessionProfile;
  session: Session;
}

export interface SessionEffect {
  created_at: String;
  effect_type: string;
  /** @nullable */
  error_text?: string | null;
  id: string;
  idempotency_key: string;
  /** @nullable */
  result_ref?: string | null;
  session_id: string;
  source_hook_id: string;
  source_turn_id: string;
  status: string;
  updated_at: String;
}

export interface SessionRuntimeSnapshot {
  compacts: Compact[];
  effects: SessionEffect[];
  messages: SessionMessage[];
  profile: SessionProfile;
  session: Session;
  soul_profile?: null | SoulProfile;
  soul_session?: null | SoulSession;
  tool_calls: ToolCall[];
  tool_results: ToolResult[];
  turns: Turn[];
}

export interface UpdateSessionRequest {
  /** @nullable */
  title?: string | null;
}

export type healthResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthResponseSuccess = healthResponse200 & {
  headers: Headers;
};
export type healthResponse = healthResponseSuccess;

export const getHealthUrl = () => {
  return `/api/v1/health`;
};

export const health = async (
  options?: RequestInit,
): Promise<healthResponse> => {
  const res = await fetch(getHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as healthResponse;
};

export type listSessionsResponse200 = {
  data: SessionSummary[];
  status: 200;
};

export type listSessionsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type listSessionsResponseSuccess = listSessionsResponse200 & {
  headers: Headers;
};
export type listSessionsResponseError = listSessionsResponse500 & {
  headers: Headers;
};

export type listSessionsResponse =
  | listSessionsResponseSuccess
  | listSessionsResponseError;

export const getListSessionsUrl = () => {
  return `/api/v1/sessions`;
};

export const listSessions = async (
  options?: RequestInit,
): Promise<listSessionsResponse> => {
  const res = await fetch(getListSessionsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSessionsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listSessionsResponse;
};

export type createSessionResponse200 = {
  data: CreateSessionResponse;
  status: 200;
};

export type createSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type createSessionResponseSuccess = createSessionResponse200 & {
  headers: Headers;
};
export type createSessionResponseError = createSessionResponse500 & {
  headers: Headers;
};

export type createSessionResponse =
  | createSessionResponseSuccess
  | createSessionResponseError;

export const getCreateSessionUrl = () => {
  return `/api/v1/sessions`;
};

export const createSession = async (
  options?: RequestInit,
): Promise<createSessionResponse> => {
  const res = await fetch(getCreateSessionUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSessionResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createSessionResponse;
};

export type getSessionResponse200 = {
  data: SessionDetail;
  status: 200;
};

export type getSessionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type getSessionResponseSuccess = getSessionResponse200 & {
  headers: Headers;
};
export type getSessionResponseError = (
  | getSessionResponse404
  | getSessionResponse500
) & {
  headers: Headers;
};

export type getSessionResponse =
  | getSessionResponseSuccess
  | getSessionResponseError;

export const getGetSessionUrl = (sessionId: string) => {
  return `/api/v1/sessions/${sessionId}`;
};

export const getSession = async (
  sessionId: string,
  options?: RequestInit,
): Promise<getSessionResponse> => {
  const res = await fetch(getGetSessionUrl(sessionId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSessionResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getSessionResponse;
};

export type updateSessionResponse200 = {
  data: SessionSummary;
  status: 200;
};

export type updateSessionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type updateSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type updateSessionResponseSuccess = updateSessionResponse200 & {
  headers: Headers;
};
export type updateSessionResponseError = (
  | updateSessionResponse404
  | updateSessionResponse500
) & {
  headers: Headers;
};

export type updateSessionResponse =
  | updateSessionResponseSuccess
  | updateSessionResponseError;

export const getUpdateSessionUrl = (sessionId: string) => {
  return `/api/v1/sessions/${sessionId}`;
};

export const updateSession = async (
  sessionId: string,
  updateSessionRequest: UpdateSessionRequest,
  options?: RequestInit,
): Promise<updateSessionResponse> => {
  const res = await fetch(getUpdateSessionUrl(sessionId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateSessionRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSessionResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateSessionResponse;
};

export type listMessagesResponse200 = {
  data: SessionMessage[];
  status: 200;
};

export type listMessagesResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type listMessagesResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type listMessagesResponseSuccess = listMessagesResponse200 & {
  headers: Headers;
};
export type listMessagesResponseError = (
  | listMessagesResponse404
  | listMessagesResponse500
) & {
  headers: Headers;
};

export type listMessagesResponse =
  | listMessagesResponseSuccess
  | listMessagesResponseError;

export const getListMessagesUrl = (sessionId: string) => {
  return `/api/v1/sessions/${sessionId}/messages`;
};

export const listMessages = async (
  sessionId: string,
  options?: RequestInit,
): Promise<listMessagesResponse> => {
  const res = await fetch(getListMessagesUrl(sessionId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listMessagesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listMessagesResponse;
};

export type runtimeSnapshotResponse200 = {
  data: SessionRuntimeSnapshot;
  status: 200;
};

export type runtimeSnapshotResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type runtimeSnapshotResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type runtimeSnapshotResponseSuccess = runtimeSnapshotResponse200 & {
  headers: Headers;
};
export type runtimeSnapshotResponseError = (
  | runtimeSnapshotResponse404
  | runtimeSnapshotResponse500
) & {
  headers: Headers;
};

export type runtimeSnapshotResponse =
  | runtimeSnapshotResponseSuccess
  | runtimeSnapshotResponseError;

export const getRuntimeSnapshotUrl = (sessionId: string) => {
  return `/api/v1/sessions/${sessionId}/runtime`;
};

export const runtimeSnapshot = async (
  sessionId: string,
  options?: RequestInit,
): Promise<runtimeSnapshotResponse> => {
  const res = await fetch(getRuntimeSnapshotUrl(sessionId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: runtimeSnapshotResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as runtimeSnapshotResponse;
};

export type sendSessionResponse200 = {
  data: SendSessionResponse;
  status: 200;
};

export type sendSessionResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type sendSessionResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type sendSessionResponseSuccess = sendSessionResponse200 & {
  headers: Headers;
};
export type sendSessionResponseError = (
  | sendSessionResponse404
  | sendSessionResponse500
) & {
  headers: Headers;
};

export type sendSessionResponse =
  | sendSessionResponseSuccess
  | sendSessionResponseError;

export const getSendSessionUrl = (sessionId: string) => {
  return `/api/v1/sessions/${sessionId}/send`;
};

export const sendSession = async (
  sessionId: string,
  sendSessionRequest: SendSessionRequest,
  options?: RequestInit,
): Promise<sendSessionResponse> => {
  const res = await fetch(getSendSessionUrl(sessionId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendSessionRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: sendSessionResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as sendSessionResponse;
};
