/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_conversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stream_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConversationDetail: {
            conversation: components["schemas"]["ConversationSummary"];
            messages: components["schemas"]["MessageRecord"][];
        };
        ConversationSummary: {
            conversation_id: components["schemas"]["String"];
            created_at: components["schemas"]["String"];
            last_message_preview?: string | null;
            title?: string | null;
            updated_at: components["schemas"]["String"];
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        HealthResponse: {
            ok: boolean;
            service: string;
        };
        MessageRecord: {
            completed_at?: null | components["schemas"]["String"];
            conversation_id: components["schemas"]["String"];
            created_at: components["schemas"]["String"];
            error?: string | null;
            message_id: components["schemas"]["String"];
            role: components["schemas"]["MessageRole"];
            state: components["schemas"]["MessageState"];
            text: string;
            updated_at: components["schemas"]["String"];
        };
        /** @enum {string} */
        MessageRole: "user" | "assistant";
        /** @enum {string} */
        MessageState: "created" | "streaming" | "completed" | "failed";
        SendMessageAccepted: {
            assistant_message: components["schemas"]["MessageRecord"];
            assistant_message_id: components["schemas"]["String"];
            conversation_id: components["schemas"]["String"];
            response_run_id: components["schemas"]["String"];
            user_message: components["schemas"]["MessageRecord"];
            user_message_id: components["schemas"]["String"];
        };
        SendMessageRequest: {
            conversation_id?: null | components["schemas"]["String"];
            text: string;
        };
        StreamEvent: {
            accepted: components["schemas"]["SendMessageAccepted"];
            /** @enum {string} */
            type: "accepted";
        } | {
            conversation_id: components["schemas"]["String"];
            delta: string;
            message_id: components["schemas"]["String"];
            /** @enum {string} */
            type: "text-delta";
        } | {
            conversation_id: components["schemas"]["String"];
            message: components["schemas"]["MessageRecord"];
            provider_response_id?: string | null;
            /** @enum {string} */
            type: "message-completed";
        } | {
            conversation_id: components["schemas"]["String"];
            error: string;
            message_id: components["schemas"]["String"];
            /** @enum {string} */
            type: "failed";
        };
        String: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stream_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Server-sent stream of StreamEvent JSON payloads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
