/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * santi-api
 * OpenAPI spec version: 0.1.0
 */
export type String = string;

export interface ConversationSummary {
  conversation_id: String;
  created_at: String;
  /** @nullable */
  last_message_preview?: string | null;
  /** @nullable */
  title?: string | null;
  updated_at: String;
}

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageRole = {
  user: "user",
  assistant: "assistant",
} as const;

export type MessageState = (typeof MessageState)[keyof typeof MessageState];

export const MessageState = {
  created: "created",
  streaming: "streaming",
  completed: "completed",
  failed: "failed",
} as const;

export interface MessageRecord {
  completed_at?: null | String;
  conversation_id: String;
  created_at: String;
  /** @nullable */
  error?: string | null;
  message_id: String;
  role: MessageRole;
  state: MessageState;
  text: string;
  updated_at: String;
}

export interface ConversationDetail {
  conversation: ConversationSummary;
  messages: MessageRecord[];
}

export interface ErrorResponse {
  code: string;
  message: string;
}

export interface HealthResponse {
  ok: boolean;
  service: string;
}

export interface SendMessageAccepted {
  assistant_message: MessageRecord;
  assistant_message_id: String;
  conversation_id: String;
  response_run_id: String;
  user_message: MessageRecord;
  user_message_id: String;
}

export interface SendMessageRequest {
  conversation_id?: null | String;
  text: string;
}

export type StreamEvent =
  | {
      accepted: SendMessageAccepted;
      type: "accepted";
    }
  | {
      conversation_id: String;
      delta: string;
      message_id: String;
      type: "text-delta";
    }
  | {
      conversation_id: String;
      message: MessageRecord;
      /** @nullable */
      provider_response_id?: string | null;
      type: "message-completed";
    }
  | {
      conversation_id: String;
      error: string;
      message_id: String;
      type: "failed";
    };

export type listConversationsResponse200 = {
  data: ConversationSummary[];
  status: 200;
};

export type listConversationsResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type listConversationsResponseSuccess = listConversationsResponse200 & {
  headers: Headers;
};
export type listConversationsResponseError = listConversationsResponse500 & {
  headers: Headers;
};

export type listConversationsResponse =
  | listConversationsResponseSuccess
  | listConversationsResponseError;

export const getListConversationsUrl = () => {
  return `/api/conversations`;
};

export const listConversations = async (
  options?: RequestInit,
): Promise<listConversationsResponse> => {
  const res = await fetch(getListConversationsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listConversationsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listConversationsResponse;
};

export type getConversationResponse200 = {
  data: ConversationDetail;
  status: 200;
};

export type getConversationResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getConversationResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type getConversationResponseSuccess = getConversationResponse200 & {
  headers: Headers;
};
export type getConversationResponseError = (
  | getConversationResponse404
  | getConversationResponse500
) & {
  headers: Headers;
};

export type getConversationResponse =
  | getConversationResponseSuccess
  | getConversationResponseError;

export const getGetConversationUrl = (conversationId: string) => {
  return `/api/conversations/${conversationId}`;
};

export const getConversation = async (
  conversationId: string,
  options?: RequestInit,
): Promise<getConversationResponse> => {
  const res = await fetch(getGetConversationUrl(conversationId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getConversationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getConversationResponse;
};

export type healthResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthResponseSuccess = healthResponse200 & {
  headers: Headers;
};
export type healthResponse = healthResponseSuccess;

export const getHealthUrl = () => {
  return `/api/health`;
};

export const health = async (
  options?: RequestInit,
): Promise<healthResponse> => {
  const res = await fetch(getHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as healthResponse;
};

export type streamMessageResponse200 = {
  data: void;
  status: 200;
};

export type streamMessageResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type streamMessageResponseSuccess = streamMessageResponse200 & {
  headers: Headers;
};
export type streamMessageResponseError = streamMessageResponse500 & {
  headers: Headers;
};

export type streamMessageResponse =
  | streamMessageResponseSuccess
  | streamMessageResponseError;

export const getStreamMessageUrl = () => {
  return `/api/messages/stream`;
};

export const streamMessage = async (
  sendMessageRequest: SendMessageRequest,
  options?: RequestInit,
): Promise<streamMessageResponse> => {
  const res = await fetch(getStreamMessageUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendMessageRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: streamMessageResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as streamMessageResponse;
};
