#!/usr/bin/env python3
"""Initialize this checkout for local development."""

from __future__ import annotations

import argparse
import shutil
import stat
import subprocess
from pathlib import Path


CURRENT_HOOK_MARKER = "mini-stim init hook"
GENERATED_HOOK_MARKERS = (
    CURRENT_HOOK_MARKER,
    "mini-stim bootstrap hook",
)

REQUIRED_TOOLS = (
    "git",
    "python3",
    "cargo",
    "pnpm",
    "sidecar",
    "flavor",
    "sh",
    "sed",
    "grep",
)

REQUIRED_PATHS = (
    "AGENTS.md",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    ".env.example",
    ".github/workflows/guard.yml",
    "flavor.toml",
    "package.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "proto/crates/transport/Cargo.toml",
    "proto/crates/server/Cargo.toml",
    "proto/crates/client/Cargo.toml",
    "apps/server/cell/Cargo.toml",
    "apps/server/soma/crates/santi-api/Cargo.toml",
    "apps/server/soma/crates/santi-core/Cargo.toml",
    "apps/server/soma/crates/santi-provider/Cargo.toml",
    "apps/client/cell/Cargo.toml",
    "apps/client/soma/Cargo.toml",
    "apps/client/soma/web/package.json",
    "packages/components/package.json",
    "packages/contracts/package.json",
    "scripts/init.py",
)

PRE_COMMIT_HOOK = f"""#!/usr/bin/env sh
# {CURRENT_HOOK_MARKER}: generated by scripts/init.py
set -eu
root=$(git rev-parse --show-toplevel)
cd "$root"

echo "==> cargo fmt"
cargo fmt --all --check

echo "==> flavor"
flavor check --root . --config flavor.toml

echo "==> sidecar"
sidecar doctor
sidecar plan --format json >/dev/null

echo "==> hook syntax"
python3 -m py_compile scripts/init.py
hooks=$(git rev-parse --git-path hooks)
sh -n "$hooks/pre-commit"
sh -n "$hooks/commit-msg"

echo "==> cargo clippy"
cargo clippy --locked --workspace --all-targets -- -D warnings

echo "==> cargo test"
cargo test --locked --workspace

echo "==> contracts"
if [ -z "${{SANTI_API_URL:-}}" ]; then
  echo "SANTI_API_URL must point at a running server soma for contract generation" >&2
  exit 1
fi
api_url=$SANTI_API_URL
curl -fsS "$api_url/api/openapi.json" -o packages/contracts/openapi.json
python3 -m json.tool --indent 2 packages/contracts/openapi.json packages/contracts/openapi.json.tmp
mv packages/contracts/openapi.json.tmp packages/contracts/openapi.json
pnpm -C packages/contracts codegen

echo "==> typecheck"
pnpm typecheck

echo "==> web build"
pnpm build

"""

COMMIT_MSG_HOOK = f"""#!/usr/bin/env sh
# {CURRENT_HOOK_MARKER}: generated by scripts/init.py
set -eu

if [ "$#" -ne 1 ] || [ ! -f "$1" ]; then
  echo "commit message file not found" >&2
  exit 1
fi

subject=$(sed -n '
/^[[:space:]]*#/d
/[^[:space:]]/ {{
  s/^[[:space:]]*//
  s/[[:space:]]*$//
  p
  q
}}
' "$1")

if [ -z "$subject" ]; then
  echo "commit subject is empty" >&2
  exit 1
fi

case "$subject" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*)
    exit 0
    ;;
esac

if ! printf '%s\\n' "$subject" | grep -Eq '^[a-z][a-z0-9-]*(/[a-z0-9-]+)*: [^[:space:]].*'; then
  echo "commit subject must look like '<area>: <imperative summary>'" >&2
  echo "actual: $subject" >&2
  exit 1
fi

if [ "${{#subject}}" -gt 72 ]; then
  echo "warning: commit subject is ${{#subject}} chars; prefer <= 72" >&2
fi
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="replace existing non-init hooks after creating a numbered .bak copy",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify required tools, entrypoints, and generated hooks without writing files",
    )
    args = parser.parse_args()

    root = repo_root()
    print(f"repository: {root}")
    check_required_tools()
    check_required_paths(root)
    if args.check:
        check_hooks(root)
        print("development environment ready")
        return 0
    install_hooks(root, force=args.force)
    print("development environment ready")
    return 0


def repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as error:
        raise SystemExit("not inside a git checkout, or git is not available") from error
    return Path(result.stdout.strip())


def check_required_tools() -> None:
    print("==> checking required tools")
    missing = [tool for tool in REQUIRED_TOOLS if shutil.which(tool) is None]
    if missing:
        raise SystemExit("missing required tool(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_TOOLS))


def check_required_paths(root: Path) -> None:
    print("==> checking repository entrypoints")
    missing = [path for path in REQUIRED_PATHS if not (root / path).is_file()]
    if missing:
        raise SystemExit("missing required path(s): " + ", ".join(missing))
    print("ok: " + ", ".join(REQUIRED_PATHS))


def install_hooks(root: Path, *, force: bool) -> None:
    print("==> installing git hooks")
    hooks_dir = git_path(root, "hooks")
    hooks_dir.mkdir(parents=True, exist_ok=True)
    install_hook(root, hooks_dir / "pre-commit", PRE_COMMIT_HOOK, force=force)
    install_hook(root, hooks_dir / "commit-msg", COMMIT_MSG_HOOK, force=force)


def check_hooks(root: Path) -> None:
    print("==> checking git hooks")
    hooks_dir = git_path(root, "hooks")
    check_hook(root, hooks_dir / "pre-commit", PRE_COMMIT_HOOK)
    check_hook(root, hooks_dir / "commit-msg", COMMIT_MSG_HOOK)


def check_hook(root: Path, path: Path, content: str) -> None:
    if not path.is_file():
        raise SystemExit(f"{display_path(root, path)} is missing; run python3 scripts/init.py")
    actual = path.read_text(encoding="utf-8", errors="replace")
    if actual != content:
        raise SystemExit(f"{display_path(root, path)} is stale; run python3 scripts/init.py")
    print(f"ok: {display_path(root, path)}")


def git_path(root: Path, suffix: str) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", suffix],
        cwd=root,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    path = Path(result.stdout.strip())
    if path.is_absolute():
        return path
    return root / path


def install_hook(root: Path, path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not is_generated_hook(path):
        if not force:
            raise SystemExit(
                f"{path} already exists and was not generated by scripts/init.py; "
                "rerun with --force to back it up and replace it"
            )
        backup = next_backup_path(path)
        path.replace(backup)
        print(f"backed up existing hook to {display_path(root, backup)}")

    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"installed {display_path(root, path)}")


def is_generated_hook(path: Path) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    return any(marker in text for marker in GENERATED_HOOK_MARKERS)


def next_backup_path(path: Path) -> Path:
    backup = path.with_name(f"{path.name}.bak")
    if not backup.exists():
        return backup

    for index in range(1, 1000):
        candidate = path.with_name(f"{path.name}.bak.{index}")
        if not candidate.exists():
            return candidate

    raise SystemExit(f"too many existing hook backups for {path}")


def display_path(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
